export const SET_DOCTORID = 'SET_DOCTORID'

export const SET_ISQUERYDOC = 'SET_ISQUERYDOC'

export const SET_NURSEID = 'SET_NURSEID'

export const SET_ISQUERYNURSE = 'SET_ISQUERYNURSE'

export const SET_PATIENTID = 'SET_PATIENTID'

export const SET_DIAGNOSISINGDOC = 'SET_DIAGNOSISINGDOC'
